version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx1g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    environment:
      - I18N_LOCALE=ja-JP
    ports:
      - 5601:5601
  collector_github:
    build:
      context: ./collector
    env_file:
      - collector_github.env
volumes:
  es_data:
    driver: local
